name: 🚀 Deploy


on:
  workflow_dispatch:
  push:
    branches:
      - 'main'


jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: d277ohioscottk.atwebpages.com
          username: 4506134_skellar
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./d277ohioscottk.atwebpages.com